/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tnqowxzrjraqeancjjhl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucW93eHpyanJhcWVhbmNqamhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NzI4OTEsImV4cCI6MjA3ODI0ODg5MX0.PG-d19VXKWv2Nnm-Z1GKCKQIRhpNpGKWAmr3X1yxerU"